### ISSUE TITLE
How to correctly import vue-openseadragon?

### ISSUE THREAD

**Issue by arjanski** [braceslab/vue-openseadragon#1]
Hello there,

I am having trouble getting to run vue-openseadragon in my Vue 2.5 single file component setup.

1) Firstly I am not sure how/where to import vue-opensadragon. Your example states

`<script type="text/javascript" src=".../dist/vue-openseadragon.min.js"></script>`

which I then put in my .vue file.

2) When I try to use <vue-openseadragon> in my template, 

```              
<vue-openseadragon :id="'image-viewer'"
                :options="{
                }">
</vue-openseadragon>
```

it throws this error

` Unknown custom element: <vue-openseadragon> - did you register the component correctly?`

 Could you point me in the right direction on how to use the module? Thanks in advance!

**Comment by simone-sanfratello** [comment]
Hi,

well, you just have to set the right the path, in the example I put 3 dots to say that :)
by the way, supposing you get ``vue-openseadragon`` from ``npm`` doing
``
npm install vue-openseadragon
``
in the root of your project, and you put the index.html in the root too, then your path to put in ``index.html`` to the lib is 
``
<script type="text/javascript" src="node_modules/vue-openseadragon/dist/vue-openseadragon.min.js"></script>
``
If you use a bundler like ``webpack`` or ``parcel`` and you scaffold your project as usual, and the path will be different

I hope this tips may help you!

**Comment by jorntx** [comment]
Hi

Thanks for taking the time to start on this wrapper component.

I was trying to put together a pull request with some fixes to your component and also ran into various issues when trying to include the component into a project. My project was initialised with newest version of vue-cli but I think that is besides the matter.

Are you able to put together a simple plunker/fiddle/codepen etc. that shows how to use the component in a hello world vue app?
